plugins {
	id 'java'
	id 'jacoco'
	id 'org.sonarqube' version '7.5.0.8588'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.unibook'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

ext {
	set('springModulithVersion', "2.1.1")
}

def coverageExcludes = [
	'**/PublisherApplication.*',
	'**/seeding/**',
	'**/config/**',
	'**/security/**',
	'**/logging/**',
	'**/entity/**',
	'**/enums/**',
	'**/event/**',
	'**/exception/**',
	'**/controller/**',
	'**/*Strategy.*',
	'**/*FileStorage*',
  '**/*StartupRunner.*'
]

sonar {
	properties {
		property 'sonar.projectKey', 'DaniloBez_UniBook-Publisher'
		property 'sonar.organization',  'danilobez'
		property 'sonar.host.url', 'https://sonarcloud.io'
		property 'sonar.java.coveragePlugin', 'jacoco'
		property 'sonar.coverage.jacoco.xmlReportPaths', "${layout.buildDirectory.get()}/reports/jacoco/test/jacocoTestReport.xml"
		property 'sonar.coverage.exclusions', coverageExcludes.join(',')
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-h2console'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.modulith:spring-modulith-starter-core'
	implementation 'org.springframework.modulith:spring-modulith-starter-jpa'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
	implementation 'io.github.java-diff-utils:java-diff-utils:4.12'
	implementation 'io.minio:minio:9.0.3'
	implementation 'me.paulschwarz:springboot4-dotenv:5.1.0'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-thymeleaf-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.modulith:spring-modulith-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.modulith:spring-modulith-bom:${springModulithVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
	jvmArgs '-XX:+EnableDynamicAgentLoading'
	// в jdk 21+ треба надавати підтвердження, щоб mockito міг мокати класи, інакше буде попередження
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true // SonarCloud потребує XML
		html.required = true // Локальний перегляд у браузері
	}
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: coverageExcludes)
		}))
	}
}

