spring.application.name=publisher

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.default-property-inclusion=non_null

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}
spring.jpa.open-in-view=false

spring.datasource.url=${DB_URL:jdbc:h2:mem:unibook_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}

spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

s3.endpoint=${S3_ENDPOINT}
s3.region=${S3_REGION}
s3.bucket=${S3_BUCKET}
s3.access-key=${S3_ACCESS_KEY}
s3.secret-key=${S3_SECRET_KEY}

file-storage.enabled=true
file-storage.type=s3

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.modulith.events.jdbc.schema-initialization.enabled=true